### ISSUE TITLE
Suggestion: Compatibility with self-hosted Omnivore installs

### ISSUE THREAD

**Issue by r0bbie** [herrherrmann/omnivore-list-popup#23]
Firstly, great extension! Simple, nice UX that just works (and is much better than the official Firefox extension! which honestly this should just become..)

Would it be possible to add a setting to allow this to be used with a self-hosted Omnivore install (i.e. an additional setting in extension prefs to override default Omnivore instance with a self-hosted one, and provide accompanying API key for self-hosted install)?

While Omnivore doesn't seem quite there yet in terms of effective self-hosting, seems like it's getting there, and would be a shame not to be able to keep using this extension!

**Comment by herrherrmann** [comment]
Hey there! Thanks for the praise.

It would definitely be easy to add this additional option, sure! Are you already self-hosting Omnivore, or is this a "future-proofing" suggestion?

**Comment by herrherrmann** [comment]
@r0bbie In version 1.3.0 I now implemented an option to set the API URL in the extension settings. I haven’t tested it with a custom instance yet though (because I don’t have one), and I could imagine that the extension still needs some additional permissions to work with it. It’d be nice if you could test it once version 1.3.0 is released (that should happen today or tomorrow).

**Comment by xiaogaozi** [comment]
Just FYI, if a custom API URL is set, an error will be reported when requesting this URL because it does not meet the [CORS policy](https://developer.chrome.com/docs/extensions/develop/concepts/network-requests) (as shown in the figure):

![CleanShot 2024-08-15 at 16 36 02@2x](https://github.com/user-attachments/assets/a6a0e796-e687-44cf-bb44-14d75dac9292)

One solution is to modify the [`host_permissions`](https://github.com/herrherrmann/omnivore-list-popup/blob/b14dbe2abc8ac82f4e17edc4dfb81a6e7eeaf83b/src/manifest.chrome.json#L18) in the `manifest.chrome.json` file and add your custom API URL to this field. However, you can't directly install the extension in the Chrome Web Store. You must fork the repository and build your own extension locally.

**Comment by herrherrmann** [comment]
@xiaogaozi Yes, you’re right that the extension permissions don’t allow for custom domains at the moment. I’ve looked into this back then and also couldn’t find any solution to make this work without rebuilding the extension yourself. Perhaps it would be more honest to remove the custom API url setting, to not confuse users. 🤔

**Comment by xiaogaozi** [comment]
For me personally, I really need the ability to customize API URL. "Omnivore List Popup" is the only Chrome extension I can currently find that supports this feature.
