### ISSUE TITLE
List only shows 10 saved items

### ISSUE THREAD

**Issue by jonasgantner** [herrherrmann/omnivore-list-popup#9]
Hi thank you very much for this extension! I like it more than the one from Omnivore themselves.
I am on chrome and for me only 10 items show in the list, eventhough I have 17 in my account / saved on omnivore.
Is this a known issue?

Also Ctrl + Click does the same for me as just click. 

Chrome Extension Version 1.1.0
Chrome Version 118.0.5993.71 (Official Build) (64-bit)

Maybe these things could be fixed. Would be amazing. Thanks!

**Comment by jonasgantner** [comment]
Thanks for the reply, good to know. I would like to adjust it in the setting if that is an option

**Comment by herrherrmann** [comment]
Yes, so there’s two things here:

1. Only the latest 10 items are shown – I would vote for adding a proper pagination here, in order to paginate through all items.
2. CTRL+Click does not open the item in a new tab – that’s a little bug that can quickly be fixed in a patch version!

I might be able to look into those things soon! And thanks for the bug report. :)

**Comment by herrherrmann** [comment]
@jonasgantner The second issue (keeping the extension popup open when CTRL is pressed when clicking an item) should be resolved in version 1.1.2 (released for Firefox, soon released for Chrome as well). The main issue still persists, until I have time to work on a proper pagination!

**Comment by herrherrmann** [comment]
@jonasgantner With version 1.4.0, there’s a proper pagination now! The page limit has also been increased to 20 items, so it should be easy to access items beyond the first 10 entries. :)
